CREATE TABLE  IF NOT EXISTS people  (
	person_id BIGINT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(20),
    last_name VARCHAR(20),
	PRIMARY KEY (person_id)
) ;

CREATE TABLE  IF NOT EXISTS sumandproduct  (
	id BIGINT NOT NULL AUTO_INCREMENT,
	v1 BIGINT NOT NULL,
    v2 BIGINT NOT NULL,
	sum BIGINT,
	product BIGINT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
) ;